language: node_js
cache: yarn

node_js: "10"

script: skip
deploy:
  provider: npm
  email: nieltansah+npmjs@gmail.com
  api_key: $NPM_API_KEY

  skip_cleanup: true
  on:
    branch: master
    tags: true
